name: hyperpay
description: A plugin to wrap HyperPay mobile SDK for iOS and Android, used to accept payments in Flutter apps using HyperPay Payments Gateway.
version: 1.0.0-dev.3
repository: https://github.com/nyartech/hyperpay

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  http: ^0.13.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nyartech.hyperpay
        pluginClass: HyperpayPlugin
      ios:
        pluginClass: HyperpayPlugin
